name: Build

on:
  push:
    tags:
      - v*

jobs:
  build-client:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Get the version
        id: get-version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install, build, and test
        run: |
          sed 's/{{version}}/v0.1.0/g' src/index.html > src/index2.html
          sed -i "" "s|v0.1.0|v0.1.1|" src/index2.html
          sed -i "" "s/v0.1.1/v0.1.2/" src/index2.html
          npm ci
          npm run build --if-present
          zip -r app-${{ steps.get-version.outputs.VERSION }}.zip dist

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: app-${{ steps.get-version.outputs.VERSION }}.zip
          asset_name: app-${{ steps.get-version.outputs.VERSION }}.zip
          tag: ${{ github.ref }}
          overwrite: true
